### ISSUE TITLE
Tag version hierarchy

### ISSUE THREAD

**Issue by fkollmann** [OctopusDeploy/push-package-action#207]
Hi, please instead of just tagging v1.1.2 also tag v1.1 and v1   (just like https://github.com/OctopusDeploy/install-octopus-cli-action). Best Regards, Felix

**Comment by hnrkndrssn** [comment]
Hey @fkollmann thanks for getting in touch.

We're in the process of overhauling our GitHub actions and as part of this work we will be tagging releases as per your suggestion.

We don't have a firm ETA as of yet when this work will be completed.

Cheers.

**Comment by jbristowe** [comment]
This is now supported! 🎉
