### ISSUE TITLE
Add Job summary to actions

### ISSUE THREAD

**Issue by ann-mwangi** [OctopusDeploy/push-package-action#245]
This is to add output and group custom Markdown content on the Actions run summary. For more info see the [GitHub announcement](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/).

This is useful to:
* Aggregate and display test results
* Generate reports
* Custom output independent of logs

**Comment by jbristowe** [comment]
Now available in 2.0! 🎉 https://github.com/OctopusDeploy/push-package-action/releases/tag/v2.0.0
