### ISSUE TITLE
Update action to use node 16

### ISSUE THREAD

**Issue by christina-30** [OctopusDeploy/push-package-action#283]
Hello, thanks for the convenient action! Unfortunately it is outdated, because it still uses the node12 runtime, can you please update to use node16?
![Screen Shot 2022-10-11 at 10 49 33 am](https://user-images.githubusercontent.com/112351798/194971351-1d58b7dc-9568-424a-9afd-f784bbde58c1.png)

**Comment by ann-mwangi** [comment]
Done as part of the [latest release](https://github.com/OctopusDeploy/push-package-action/releases/tag/v2.2.0).
