### ISSUE TITLE
v3 doesn't support whitespaces in Octopus Space name

### ISSUE THREAD

**Issue by gitsidgo** [OctopusDeploy/push-package-action#300]
We have whitespaces in our Octopus space name like 'My - Space'. 
Earlier we were using version v2 of push-package-action and there were no issues in pushing packages to the above space with whitespaces in its name. 
Of late we have updated to v3 and the push fails with the following error:

```Error: Error: Invalid Literal "https://my-octopus.my-org.com/api/spaces?partialName=My - Space&skip=0&take=<some_number>"```

Is there any workaround/solution for this?

**Comment by benPearce1** [comment]
Hi @gitsidgo, 

This was a bug that was introduced in the most recent release. This release has been deleted.
There will be a fix coming out today.
